import type { FormTemplate } from './types';
import { generateId } from './utils';

export const formTemplates: FormTemplate[] = [
  {
    id: 'customer-satisfaction',
    name: 'Customer Satisfaction',
    description: 'Measure customer happiness with your product or service',
    category: 'survey',
    icon: '😊',
    questions: [
      {
        id: generateId(),
        type: 'rating',
        title: 'How satisfied are you with our product?',
        required: true,
        maxRating: 5,
      },
      {
        id: generateId(),
        type: 'multiple_choice',
        title: 'How often do you use our product?',
        required: true,
        options: [
          { id: generateId(), text: 'Daily' },
          { id: generateId(), text: 'Weekly' },
          { id: generateId(), text: 'Monthly' },
          { id: generateId(), text: 'Rarely' },
        ],
      },
      {
        id: generateId(),
        type: 'text',
        title: 'What could we improve?',
        required: false,
      },
      {
        id: generateId(),
        type: 'linear_scale',
        title: 'How likely are you to recommend us?',
        required: true,
        scaleMin: 0,
        scaleMax: 10,
        scaleMinLabel: 'Not likely',
        scaleMaxLabel: 'Very likely',
      },
    ],
  },
  {
    id: 'event-registration',
    name: 'Event Registration',
    description: 'Collect attendee information for your event',
    category: 'registration',
    icon: '🎫',
    questions: [
      { id: generateId(), type: 'text', title: 'Full Name', required: true },
      {
        id: generateId(),
        type: 'email',
        title: 'Email Address',
        required: true,
      },
      {
        id: generateId(),
        type: 'phone',
        title: 'Phone Number',
        required: false,
      },
      {
        id: generateId(),
        type: 'dropdown',
        title: 'How did you hear about this event?',
        required: true,
        options: [
          { id: generateId(), text: 'Social Media' },
          { id: generateId(), text: 'Email' },
          { id: generateId(), text: 'Friend/Colleague' },
          { id: generateId(), text: 'Website' },
        ],
      },
      {
        id: generateId(),
        type: 'checkbox',
        title: 'Dietary requirements',
        required: false,
        options: [
          { id: generateId(), text: 'Vegetarian' },
          { id: generateId(), text: 'Vegan' },
          { id: generateId(), text: 'Gluten-free' },
          { id: generateId(), text: 'None' },
        ],
      },
    ],
  },
  {
    id: 'general-knowledge-quiz',
    name: 'General Knowledge Quiz',
    description: 'Test knowledge with auto-scoring and timer',
    category: 'quiz',
    icon: '🧠',
    timerEnabled: true,
    timerMinutes: 10,
    questions: [
      {
        id: generateId(),
        type: 'multiple_choice',
        title: 'What is the capital of France?',
        required: true,
        points: 10,
        options: [
          { id: generateId(), text: 'London', isCorrect: false },
          { id: generateId(), text: 'Paris', isCorrect: true },
          { id: generateId(), text: 'Berlin', isCorrect: false },
          { id: generateId(), text: 'Madrid', isCorrect: false },
        ],
      },
      {
        id: generateId(),
        type: 'multiple_choice',
        title: 'Which planet is known as the Red Planet?',
        required: true,
        points: 10,
        options: [
          { id: generateId(), text: 'Venus', isCorrect: false },
          { id: generateId(), text: 'Mars', isCorrect: true },
          { id: generateId(), text: 'Jupiter', isCorrect: false },
          { id: generateId(), text: 'Saturn', isCorrect: false },
        ],
      },
      {
        id: generateId(),
        type: 'yes_no',
        title: 'Is the Earth flat?',
        required: true,
        points: 5,
        options: [
          { id: generateId(), text: 'Yes', isCorrect: false },
          { id: generateId(), text: 'No', isCorrect: true },
        ],
      },
    ],
  },
  {
    id: 'quick-poll',
    name: 'Quick Poll',
    description: 'Get instant opinions with a simple one-question poll',
    category: 'poll',
    icon: '📊',
    questions: [
      {
        id: generateId(),
        type: 'multiple_choice',
        title: 'What do you prefer?',
        required: true,
        options: [
          { id: generateId(), text: 'Option A' },
          { id: generateId(), text: 'Option B' },
          { id: generateId(), text: 'Option C' },
        ],
      },
    ],
  },
  {
    id: 'feedback-form',
    name: 'Feedback Form',
    description: 'Collect feedback on a product, service, or experience',
    category: 'feedback',
    icon: '💬',
    questions: [
      {
        id: generateId(),
        type: 'rating',
        title: 'Overall experience',
        required: true,
        maxRating: 5,
      },
      {
        id: generateId(),
        type: 'checkbox',
        title: 'What did you like?',
        required: false,
        options: [
          { id: generateId(), text: 'Quality' },
          { id: generateId(), text: 'Speed' },
          { id: generateId(), text: 'Price' },
          { id: generateId(), text: 'Support' },
        ],
      },
      {
        id: generateId(),
        type: 'text',
        title: 'Additional comments',
        required: false,
      },
    ],
  },
  {
    id: 'employee-survey',
    name: 'Employee Engagement',
    description: 'Gauge workplace satisfaction and culture',
    category: 'survey',
    icon: '👔',
    questions: [
      {
        id: generateId(),
        type: 'linear_scale',
        title: 'How engaged do you feel at work?',
        required: true,
        scaleMin: 1,
        scaleMax: 10,
        scaleMinLabel: 'Not engaged',
        scaleMaxLabel: 'Highly engaged',
      },
      {
        id: generateId(),
        type: 'rating',
        title: 'Rate your work-life balance',
        required: true,
        maxRating: 5,
      },
      {
        id: generateId(),
        type: 'multiple_choice',
        title: 'Do you feel valued by your manager?',
        required: true,
        options: [
          { id: generateId(), text: 'Always' },
          { id: generateId(), text: 'Often' },
          { id: generateId(), text: 'Sometimes' },
          { id: generateId(), text: 'Rarely' },
        ],
      },
      {
        id: generateId(),
        type: 'text',
        title: 'What would improve your experience?',
        required: false,
      },
    ],
  },
  {
    id: 'contact-form',
    name: 'Contact Form',
    description: 'Simple contact form for websites',
    category: 'feedback',
    icon: '✉️',
    questions: [
      { id: generateId(), type: 'text', title: 'Your Name', required: true },
      {
        id: generateId(),
        type: 'email',
        title: 'Email Address',
        required: true,
      },
      {
        id: generateId(),
        type: 'phone',
        title: 'Phone (optional)',
        required: false,
      },
      {
        id: generateId(),
        type: 'dropdown',
        title: 'Subject',
        required: true,
        options: [
          { id: generateId(), text: 'General Inquiry' },
          { id: generateId(), text: 'Support' },
          { id: generateId(), text: 'Sales' },
          { id: generateId(), text: 'Partnership' },
        ],
      },
      { id: generateId(), type: 'text', title: 'Message', required: true },
    ],
  },
  {
    id: 'course-evaluation',
    name: 'Course Evaluation',
    description: 'Evaluate teaching and course quality',
    category: 'survey',
    icon: '🎓',
    questions: [
      {
        id: generateId(),
        type: 'rating',
        title: 'Rate the instructor',
        required: true,
        maxRating: 5,
      },
      {
        id: generateId(),
        type: 'rating',
        title: 'Rate the course content',
        required: true,
        maxRating: 5,
      },
      {
        id: generateId(),
        type: 'linear_scale',
        title: 'How likely are you to recommend this course?',
        required: true,
        scaleMin: 1,
        scaleMax: 10,
        scaleMinLabel: 'Not at all',
        scaleMaxLabel: 'Definitely',
      },
      {
        id: generateId(),
        type: 'text',
        title: 'What was the best part of the course?',
        required: false,
      },
      {
        id: generateId(),
        type: 'text',
        title: 'Suggestions for improvement',
        required: false,
      },
    ],
  },
];
